journal/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("journal.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("tah/", include("journal.tah.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

journal/journal/tah/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from journal.tah.views import (teor, calculation1, results, downloadfile)

app_name = "tah"
urlpatterns = [
    path('teor/<int:id>', view=teor, name="teor"),
    path('calculation1/', view=calculation1, name="calculation1"),
    path('results/', view=results, name="results"),
    path('downloadfile/', view=downloadfile, name="downloadfile"),

]

journal/journal/users/urls.py
from django.urls import path

from journal.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

journal/journal/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Tah-journal.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

journal/journal/tah/forms.py
from termios import FF1
from unittest.util import _MAX_LENGTH
from django import forms
from django.forms import formset_factory


class JournalForm(forms.Form):
    journal_name = forms.CharField(label='Название журнала', max_length=100)
    meters = forms.CharField(label='Метры', max_length=100)
    meters_corrections = forms.CharField(label='Метры исправленные', max_length=100)

class StationForm(forms.Form):
    station_name = forms.CharField(label='station_name', max_length=100)
    station_height = forms.FloatField(label='station_height')
    sighting_points1 = forms.CharField(label='sighting_points1', max_length=100)
    sighting_points2 = forms.CharField(label='sighting_points2', max_length=100)
    sighting_points3 = forms.CharField(label='sighting_points3', max_length=100)
    sighting_points4 = forms.CharField(label='sighting_points4', max_length=100)
    gorizontal_angle_gradus1 = forms.IntegerField(label='gorizontal_angle_gradus1')
    gorizontal_angle_gradus2 = forms.IntegerField(label='gorizontal_angle_gradus2')
    gorizontal_angle_gradus3 = forms.IntegerField(label='gorizontal_angle_gradus3')
    gorizontal_angle_gradus4 = forms.IntegerField(label='gorizontal_angle_gradus4')
    gorizontal_angle_min1 = forms.FloatField(label='gorizontal_angle_min1')
    gorizontal_angle_min2 = forms.FloatField(label='gorizontal_angle_min2')
    gorizontal_angle_min3 = forms.FloatField(label='gorizontal_angle_min3')
    gorizontal_angle_min4 = forms.FloatField(label='gorizontal_angle_min4')
    sighting_points_neighbors1 = forms.CharField(label='sighting_points_neighbors1', max_length=100)
    sighting_points_neighbors2 = forms.CharField(label='sighting_points_neighbors2', max_length=100, required=False)
    sighting_points_neighbors_height1 = forms.CharField(label='sighting_points_neighbors_height1', max_length=100)
    sighting_points_neighbors_height2 = forms.CharField(label='sighting_points_neighbors_height2', max_length=100, required=False)
    vertical_angle_gradus1 = forms.CharField(label='vertical_angle_gradus1', max_length=100)
    vertical_angle_gradus2 = forms.CharField(label='vertical_angle_gradus2', max_length=100)
    vertical_angle_gradus3 = forms.CharField(label='vertical_angle_gradus3', max_length=100, required=False)
    vertical_angle_gradus4 = forms.CharField(label='vertical_angle_gradus4', max_length=100, required=False)
    vertical_angle_min1 = forms.CharField(label='vertical_angle_min1', max_length=100)
    vertical_angle_min2 = forms.CharField(label='vertical_angle_min2', max_length=100)
    vertical_angle_min3 = forms.CharField(label='vertical_angle_min3', max_length=100, required=False)
    vertical_angle_min4 = forms.CharField(label='vertical_angle_min4', max_length=100, required=False)
    rail1 = forms.CharField(label='rail1', max_length=100)
    rail2 = forms.CharField(label='rail2', max_length=100)
    rail3 = forms.CharField(label='rail3', max_length=100, required=False)
    rail4 = forms.CharField(label='rail4', max_length=100, required=False)
    #right_left = forms.CharField(label='right_or_left1', max_length=100)
    # right_left = forms.CharField(label='f6', max_length=100)
    # right_left_neighbors = forms.CharField(label='f3', max_length=100)
    # right_left = forms.CharField(label='f6', max_length=100)
    # right_left_neighbors = forms.CharField(label='f3', max_length=100)
    # right_left1 = forms.CharField(label='right_or_left1', max_length=100)
    # right_left2 = forms.CharField(label='right_or_left2', max_length=100)
    # right_left3 = forms.CharField(label='right_or_left3', max_length=100)
    # right_left4 = forms.CharField(label='right_or_left4', max_length=100)

class VedomostForm(forms.Form):
    array_dir_angle_gr = forms.IntegerField(label='array_dir_angle_gr')
    array_dir_angle_min = forms.FloatField(label='array_dir_angle_min')
    last_dir_angle_gr   = forms.IntegerField(label='last_dir_angle_gr')
    last_dir_angle_min = forms.FloatField(label='last_dir_angle_min')

# class TaheometriaForm(forms.Form):
#     pass
 








StationFormset = formset_factory(StationForm, extra=1)

journal/journal/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

journal/journal/tah/views.py
import os
from re import U
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse, Http404
import datetime
from .forms import JournalForm, StationFormset, StationForm, VedomostForm
from .models import Journal, Station, Vedomost
from journal.users.models import User
from .calculations import calculations 


@login_required
def calculation1(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # raise Exception
        # create a form instance and populate it with data from the request:
        form1 = JournalForm(request.POST)
        form2 = StationFormset(request.POST)
        form3 = VedomostForm(request.POST)

        # check whether it's valid:
        if form1.is_valid() and form2.is_valid() and form3.is_valid():
            print(form1.cleaned_data['journal_name'])
            stations = int(request.POST['form-TOTAL_FORMS'])
            print(stations)
            username = request.user.username
            u = User.objects.get(username=username)
            #ИЛЬЯ, ДЕЛАЙ ТУТ
            j = Journal.objects.create(journal_name=form1.cleaned_data['journal_name'], meters=form1.cleaned_data['meters'], meters_corrections=form1.cleaned_data['meters_corrections'], date_of_creation=datetime.datetime.now(), user=u)
            JournalIN = {"meters": form1.cleaned_data['journal_name'], "meters_corrections": form1.cleaned_data['meters'] }
            for station in form2.cleaned_data:
                print(station)
                # Station.objects.create(journal=j,
                #     station_name=station['station_name'],
                #     station_height=station['station_height'],
                #     sighting_points1=station['sighting_points1'],
                #     sighting_points2=station['sighting_points2'],
                #     sighting_points3=station['sighting_points3'],
                #     sighting_points4=station['sighting_points4'],
                #     gorizontal_angle_gradus1=station['gorizontal_angle_gradus1'],
                #     gorizontal_angle_gradus2=station['gorizontal_angle_gradus2'],
                #     gorizontal_angle_gradus3=station['gorizontal_angle_gradus3'],
                #     gorizontal_angle_gradus4=station['gorizontal_angle_gradus4'],
                #     gorizontal_angle_min1=station['gorizontal_angle_min1'],
                #     gorizontal_angle_min2=station['gorizontal_angle_min2'],
                #     gorizontal_angle_min3=station['gorizontal_angle_min3'],
                #     gorizontal_angle_min4=station['gorizontal_angle_min4'],
                #     sighting_points_neighbors1=station['sighting_points_neighbors1'],
                #     sighting_points_neighbors2=station['sighting_points_neighbors2'],
                #     sighting_points_neighbors_height1=station['sighting_points_neighbors_height1'],
                #     sighting_points_neighbors_height2=station['sighting_points_neighbors_height2'],
                #     vertical_angle_gradus1=station['vertical_angle_gradus1'],
                #     vertical_angle_gradus2=station['vertical_angle_gradus2'],
                #     vertical_angle_gradus3=station['vertical_angle_gradus3'],
                #     vertical_angle_gradus4=station['vertical_angle_gradus4'],
                #     vertical_angle_min1=station['vertical_angle_min1'],
                #     vertical_angle_min2=station['vertical_angle_min2'],
                #     vertical_angle_min3=station['vertical_angle_min3'],
                #     vertical_angle_min4=station['vertical_angle_min4'],
                #     rail1=station['rail1'],
                #     rail2=station['rail2'],
                #     rail3=station['rail3'],
                #     rail4=station['rail4'],                                    
                #     )
                
            # v = Vedomost.objects.create( array_dir_angle_gr = form3.cleaned_data['array_dir_angle_gr'], array_dir_angle_min = form3.cleaned_data['array_dir_angle_min'], last_dir_angle_gr = form3.cleaned_data['last_dir_angle_gr'], last_dir_angle_min = form3.cleaned_data['last_dir_angle_min'])
            #ИЛЬЯ, ДЕЛАЙ ТУТ
            calculations()            
            return render(request, 'tah/results.html', {'form1': form1, 'form2': form2, 'form3': form3}) 
        else:
            return render(request, 'tah/calculation1.html', {'form1': form1, 'form2': form2, 'form3': form3})
    else:
        form1 = JournalForm()
        form2 = StationFormset()
        form3 = VedomostForm()

    return render(request, 'tah/calculation1.html', {'form1': form1, 'form2': form2, 'form3': form3})


def teor(request, id):
    teorId = id
    return render(request, f'teor/teor{teorId}.html')


def results(request):
    if request.method == 'POST':
        pass
    else:
        pass
    return render(request, 'tah/results.html')

def downloadfile(request):
        return render(request, 'tah/TahJournal.xlsx')
        

    
    
    

journal/journal/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

journal/journal/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Tah-journal{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Расчёт данных для заполнения тахеометрического журнала">
    <meta name="author" content="Daniel Roy Greenfeld">
    
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    
    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>
    <div class = "page">
      <div id="header">    
        <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" Width="80" Height="40"></a>
        <a class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">О нас</a>
        </a>
        {% if request.user.is_authenticated %}
          <a class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% translate "Мой профиль" %}</a>
          </a>
          <a class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Выйти" %}</a>
          </a>
        {% else %}
          {% if ACCOUNT_ALLOW_REGISTRATION %}
          <a class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Зарегистрироватся" %}</a>
          </a>
          {% endif %}
          <a class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Войти" %}</a>
          </a>
        {% endif %}
        <div class="hamburger-menu">
          <input id="menu__toggle" type="checkbox" />
          <label class="menu__btn" for="menu__toggle">
            <span></span>
          </label>
          <ul class="menu__box">
            <h1>Теоретическое обоснование для теодолита 2Т30П</h1>
            <li><a class="menu__item" href="{% url 'tah:teor' id=1 %}">Рекогносцировка хода</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=2 %}">Проложение тахеометрического хода</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=3 %}">Порядок измерений на пункте хода</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=4 %}">Камеральная обработка результатов измерений</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=5 %}">Ведомость вычисления координат точек хода</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=6 %}">Ведомость вычисления высот тахеометрического хода</a></li>
            <li><a class="menu__item" href="{% url 'tah:teor' id=7 %}">Тахеометрическая съемка</a></li>
          </ul>
        </div>
      </div>
       
      <div class="container">

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}      
        {% comment %} <p>Добро пожаловать к расчетам!)</p>
        <li><a class="menu__item" href="{% url 'tah:calculation1' %}">Рекогносцировка хода</a></li> {% endcomment %}
        <div id ="mainpadgecontainer">
          <div class = "mainlogo"><img src="{% static 'images/logo.png' %}" alt = "Информаторы"></div>
          <div class = 'maindiv'>
            <div class = "maintext"><p>Данное приложение призвано автоматизировать расчёт тахеометрического журнала.</p></div>
            <div class = "mainbutton"><a class="btn" href="{% url 'tah:calculation1' %}">Начать расчёт</a></div>
          </div>
        </div>  
        {% endblock content %}
      </div>

      {% block modal %}{% endblock modal %}

      {% block inline_javascript %}
      {% comment %}
      Script tags with only code, no src (defer by default). To run
      with a "defer" so that you run inline code:
      <script>
        window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
      </script>
      {% endcomment %}
      <div id="footer">
        <div id="x1">&copy;Информаторы 2022</div>
        <div id="x2"><img src="{% static 'images/MIIGAiK.png' %}" Width="75" Height="95"></div>
      </div>
       {% endblock inline_javascript %}
  </div>
  </body>
</html>